// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class MapController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string perpetuality_map = "perpetuality_map";
                public readonly string perpetuality_map_js = "perpetuality_map_js";
            }
            public readonly string Index = "~/Views/Map/Index.cshtml";
            public readonly string perpetuality_map = "~/Views/Map/perpetuality_map.css";
            public readonly string perpetuality_map_js = "~/Views/Map/perpetuality_map.js";
            static readonly _imagesClass s_images = new _imagesClass();
            public _imagesClass images { get { return s_images; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _imagesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string cloudy = "cloudy";
                    public readonly string default_image = "default-image";
                    public readonly string green = "green";
                    public readonly string nuclear_power_plant = "nuclear-power-plant";
                    public readonly string orange = "orange";
                    public readonly string red = "red";
                    public readonly string solar_panel = "solar_panel";
                    public readonly string sources = "sources";
                }
                public readonly string cloudy = "~/Views/Map/images/cloudy.jpg";
                public readonly string default_image = "~/Views/Map/images/default-image.jpeg";
                public readonly string green = "~/Views/Map/images/green.png";
                public readonly string nuclear_power_plant = "~/Views/Map/images/nuclear-power-plant.png";
                public readonly string orange = "~/Views/Map/images/orange.png";
                public readonly string red = "~/Views/Map/images/red.png";
                public readonly string solar_panel = "~/Views/Map/images/solar_panel.jpg";
                public readonly string sources = "~/Views/Map/images/sources";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
